changelog:
  categories:
    - title: "What's new"
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Other
      labels:
        - "*"
